name: query_wizard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.16.0
  flutter_localized_locales: ^2.0.1
  flutter_treeview:
      path: ./packages/flutter_treeview
  equatable: ^2.0.0
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mockito: ^5.0.3

flutter:

  generate: true
  uses-material-design: true
